stages:
  prepare:
    cmd: python src/prepare.py data/raw/hmnist_28_28_L.csv data/prepared
    deps:
      - data/raw/hmnist_28_28_L.csv
      - src/prepare.py
    outs:
      - data/prepared
  train:
    cmd: python src/train.py data/prepared models
    deps:
      - data/prepared
      - src/train.py
    outs:
      - models
